spring:
  cloud:
    stream:
      bindings:
        userDeleted-in-0:
          destination: users.delete
  application:
    name: tweet-service
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka